### ISSUE TITLE
Repeatability for VD-CMA

### ISSUE THREAD

**Issue by agrayver** [beniz/libcmaes#105]
For testing purposes I use constant seed like that:

CMAParameters<> cmaparams(x0, sigma, -1, 12345, gp);

This gives reproducible results with aCMAES. However, when I switch to VD-CMA, even with the fixed seed specified, results change for every run.

Any idea?

**Comment by beniz** [comment]
Thanks for catching this. I can reproduce, so I will look at it and report here.

**Comment by beniz** [comment]
Here, fixed, due to the init of a complementary vector, which is now taking the seed into account. The fix in on 'dev' branch, you can either pull that branch or report the fix on the master's source code if you like, it is really a very tiny change in the code.

**Comment by agrayver** [comment]
Done. Thanks for quick patch.
