### ISSUE TITLE
Updating documentation

### ISSUE THREAD

**Issue by agrayver** [beniz/libcmaes#109]
Documentation of the the method CMAParameters::set_str_algo(const std::string &algo) says:

sets the optimization algorithm.
algo as string from cmaes,ipop,bipop,acmaes,aipop,abipop,
sepcmaes,sepipop, sepbipop,sepacmaes,sepaipop,sepabipop

Is there any reason this list misses VD algorithms?

**Comment by beniz** [comment]
I believe the comment header in the code is missing the new entry. The documentation is automatically generated from it (but triggered by hand), and I usually do it for every new release.
 
You can use ' vdcma', 'vdipopcma', 'vdbipopcma'. The code has support for these: https://github.com/beniz/libcmaes/blob/dev/src/cmaparameters.h#L297

A header fix will follow.
