### ISSUE TITLE
lib crashes if `lambda` is passed as 0

### ISSUE THREAD

**Issue by beniz** [beniz/libcmaes#119]
Example:
```
 ./test_functions -fname rosenbrock -dim 20 -lambda 0
Floating point exception
```

**Comment by beniz** [comment]
Made a simple fix available, that uses default value if `lambda<2`. This has the advantage of not compromising a quick run, and the drawback of not informing him/her of the mistake.

**Comment by nikohansen** [comment]
Makes sense to me, one could consider firing a warning in verbose mode.

**Comment by beniz** [comment]
> one could consider firing a warning in verbose mode

Just FTR, this is tricky because the default value of lambda is set in the Parameters constructor, and the verbose/non-verbose mode is undecided at this stage. So in practice it is possible to set a warning message, but not to condition it upon the verbosity on/off option. For now I'd see this as an 'autocorrect' for a user mistake.
