### ISSUE TITLE
Numpy extension header not found

### ISSUE THREAD

**Issue by nikohansen** [beniz/libcmaes#120]
While it just worked a few minutes ago, now I get 

    checking for Numpy include directory... checking for /numpy/arrayobject.h... no
    configure: error: Numpy extension header not found

when I call `./configure`. I believe the only thing I did in between was `git checkout dev` and `git checkout master` and `git pull`.

**Comment by beniz** [comment]
Numpy detection is very recent (#113), not in master, so I'd do:
```
git checkout dev
git pull
./autogen.sh
```
and then `configure`.

**Comment by nikohansen** [comment]
thanks, I guess I missed to do `./autogen.sh` again.

**Comment by beniz** [comment]
When the configuration script changes between commits, the ./autogen.sh is required (or `autoreconf`).
