### ISSUE TITLE
Switch-off threads

### ISSUE THREAD

**Issue by agrayver** [beniz/libcmaes#127]
Is there a way to switch-off OMP upon configuration? I.e. eliminate dependence of the libcmaes on OMP.
Thank you.

**Comment by beniz** [comment]
Can you give more details about what you need to achieve or what is the way to that ? 

To my knowledge, OMP is within gcc nowadays (and not supported by clang), so I'm not sure the 'dependence' can be eliminated. However, you can definitely control the number of threads, which means you can max it to one for instance.

**Comment by agrayver** [comment]
I was getting undefined reference errors. When you said that openmp is a part of gcc, I found out that I had to compile and link with -fopenmp flag. Now it compiles fine, sorry for bothering.
