### ISSUE TITLE
Memory estimation

### ISSUE THREAD

**Issue by Gregwar** [beniz/libcmaes#138]
Hello, I'm running CMA-ES with following parameters:

    dimensions: 8
    lambda: 64
    algo: BIPOP
    restarts: 3
    max_iter: 150
    
(I run it on a multithreaded computer, the fitness function is really expansive, like seconds)
May CMA-ES itself consume a lot of memory for such an operation?

**Comment by beniz** [comment]
What makes you think CMA-ES may consume a lot of memory ? 8-D is not an issue, and `lambda=64` is a reasonable value.

If your fitness function takes resources and time to evaluate, there are a few strategies you can use to speed CMA-ES up a little bit. First is making parallel calls (if you have enough resources), see https://github.com/beniz/libcmaes/wiki/Multithreading. Second is to use the surrogate approach to lower the number of calls to the fitness, but this is more experimental.

**Comment by Gregwar** [comment]
Because valgrind says that my simulation method doesn't have a leak, but running my simulation with CMA-ES makes my program consume more and more memory until exhausting resources, this is why I'm investigating on where the bytes are lost

I'm already multithreading, running it on a 48 cores machine with 64Go RAM, it starts swapping after an hour

**Comment by Gregwar** [comment]
Maybe I'll separate CMA-ES from my logic by executing external programs, I'll then be able to check if it still grows

**Comment by beniz** [comment]
OK, if valgrind doesn't report anything and assuming you are linking against the code of the fitness function, it may come from the history that is kept in memory for computing some statistics.

Try `set_max_hist(3)` for instance on your `CMAParameters` objects and let me know if this helps.

**Comment by Gregwar** [comment]
OK, I'll give it a try

**Comment by Gregwar** [comment]
Memory should get stable after iteration 3, right?

**Comment by beniz** [comment]
Not exactly because other information is retained and grows within `CMASolutions` objects. But putting a cap on the maximum retained history has helped me in the past IIRC.

**Comment by Gregwar** [comment]
OK
And does it also helps for the algorithm normalizing parameters so libcmaes handle values between 0 and 1 for instance?

**Comment by beniz** [comment]
It is of tremendous help to the search procedure to re-scale the parameters so that the sensitivity is similar across all dimensions. Using the `linScalingStrategy` does that for you automatically.

**Comment by nikohansen** [comment]
What is the reason you don't use the default value for `max_iter`?

**Comment by Gregwar** [comment]
@nikohansen you think I should let it as default?
I've externalized the computation of my fitness by calling another process (w/ popen & pclose), this seems to solve the memory exhausting (however I still don't understand why since Va)
Anyway, the lib seems to converge now but I have problem with adjusting stopping criterias

The symptom is that it converge reasonably fast and takes really long time to overtune the result by tweaking really small things, I think what I need is adjusting the `ftolerance`, is this right?
Should I also adjust the maximum number of restarts?

**Comment by beniz** [comment]
Yes you can change the tolerance and the maximum number of restarts.

**Comment by Gregwar** [comment]
OK, I eventually reached a quite good configuration, thank you very much for yours answers
