### ISSUE TITLE
Limit maximum number of threads.

### ISSUE THREAD

**Issue by abhinavagarwal07** [beniz/libcmaes#147]
How to limit maximum number of threads running concurrently?

**Comment by beniz** [comment]
See https://eigen.tuxfamily.org/dox/TopicMultiThreading.html
If you are calling from C++, it might work to use the `setNbThreads` from Eigen. Let me know if it doesn't.
Default is using all threads.

**Comment by kjfergu** [comment]
Bit late to the party here, but in C++ you can use

    omp_set_num_threads()

    omp_set_dynamic(false)

The former will set the maximum number of threads that OMP will use. The latter says that OMP will always use the maximum number of threads. OMP will try to 'smartly' distribute the load without this flag, meaning it may only use 3 or 4 threads out of a maximum of 8 (for example). I've found it to be a bit unpredictable with expensive objective functions, so I set it to false.
