### ISSUE TITLE
Request for clarification on documentation for bounds

### ISSUE THREAD

**Issue by medrimonia** [beniz/libcmaes#148]
From the documentation available [here](https://github.com/beniz/libcmaes/wiki/Defining-and-using-bounds-on-parameters) and [here](https://github.com/beniz/libcmaes/wiki/Using-parameter-space-transforms-known-as-genotype-phenotype-transforms). It is not clearly stated that one has to call `gp.pheno(solution)` in order to get the values of the parameters in the initial parameter space.

I had some trouble to get the implementation working properly until I start searching informations in the last commits and found [this page](https://github.com/beniz/libcmaes/commit/75b8562710935cab34739ee9e53af3e3e93b910f). By inspecting the code of the print function I quickly understood my mistake.

Since I just started using cmaes, this information might be obvious for frequent user, but I have the feeling that newcomers might be helped by adding a mention of `gp.pheno(solution)` inside those two pages.

**Comment by beniz** [comment]
Hi, sorry about that. I've checked and it seems the Wiki is opened to users who'd like to contribute, could you fix the wiki as you see fit by any chance ? Thanks.

**Comment by medrimonia** [comment]
I have brought some tiny modifications to the wiki, thank you for your quick answer.

**Comment by beniz** [comment]
Thank you!

**Comment by marija-p** [comment]
@medrimonia  I came across this issue and just wanted to say: thanks a lot for the contribution! You saved me a big headache. :+1:

**Comment by medrimonia** [comment]
@marija-p you're welcome. I'm glad it helped you.
