### ISSUE TITLE
CMake Config File

### ISSUE THREAD

**Issue by fergu** [beniz/libcmaes#157]
This is just an enhancement request.

I use libcmaes in an external C++ program which I am developing. I am attempting to migrate my own project to cmake for building, and since I use libcmaes, it would be nice to be able to call find_package(cmaes) to find and set up CMAES for usage. It is my understanding that a UseCmaes.cmake or CmaesConfig.cmake file is needed for this, which I do not believe libcmaes creates during building.

I, unfortunately, am still learning CMake, so I am not well versed enough to write the file myself yet. If I get to that point, I'll try to write it and submit a pull request, but I wanted to put this here in case anyone else wants to take a swing.

**Comment by beniz** [comment]
You should be able to quickly get there by modifying an existing FindXXX.cmake file such as https://github.com/BVLC/caffe/blob/master/cmake/Modules/FindOpenBLAS.cmake
When you are successful, your PR is welcome.

**Comment by jcnorby** [comment]
Has this not been implemented yet? I don't see a Findlibcmaes.cmake anywhere...

**Comment by beniz** [comment]
Not that I know.

**Comment by jcnorby** [comment]
I made one very naively which compiles, but I get a seg fault similar to
that in issue #99 (although I don't expect I'll have to reinstall Ubuntu).
I attempted to follow along with the proposed solution there but it was a
little to different from my use case to work. Should I open this as a new
issue and explain what is going on there?

**Comment by beniz** [comment]
> Should I open this as a new
> issue and explain what is going on there?

If it is not related to CMake, yes.

**Comment by fidergo-stephane-gourichon** [comment]
@jcnorby can you share your attempt? I'm considering contributing with a PR.

**Comment by phbasler** [comment]
In lights of the 0.9.6 release I would like to use this issue and ask if it would be possible to include an export into your Toplevel CMakeLists.txt so that find_package(libcmaes) can be used.
Do you have any plans for this?
