### ISSUE TITLE
Segfault with Eigen 3.3

### ISSUE THREAD

**Issue by marija-p** [beniz/libcmaes#164]
Hi there! :smile:  I'm running Ubuntu Linux 16.04 (Eigen 3.3-beta1-2) on an Lenovo X1 Yoga laptop. I'm trying to use libcmaes to perform CMA-ES optimization for a drone path-planning application using the [Robot Operating System](http://www.ros.org/). However, when calling [bounded optimization](https://github.com/beniz/libcmaes/wiki/Defining-and-using-bounds-on-parameters) example within my framework, a very annoying Eigen segfault error is produced (screenshot from GDB):

![segfault](https://user-images.githubusercontent.com/14071766/28607516-88fa734a-71dc-11e7-8342-cd94241a084a.jpeg)

This problem only occurs when I run the optimization routine **from my ROS node,** whether other things with Eigen are happening, as well. In an isolated unit test, the function call works perfectly fine. The entire pipeline also works on my other machine which is running Ubuntu Linux 14.04 LTS (Eigen 3.2.0).

Very strange. I'm suspecting some Eigen alignment errors. Has anyone else experienced this, or has ideas on how to fix this? I spent so much time! :sob: 

Thanks, Masha

**Comment by beniz** [comment]
Hi @marija-p can you try to revert to commit https://github.com/beniz/libcmaes/commit/bd05321dcc4dfade26d4e51a716a652379fd2b34 and see whether the error still occurs ?

**Comment by marija-p** [comment]
@beniz  Thanks for the reply. I'll have a look soon, and let you know here. :)

**Comment by marija-p** [comment]
@beniz Strangely, despite the fact that I re-installed the library, I can't seem to replicate the issue anymore, even when I use master and enable vectorization! I'll keep you updated if I come across this problem again, given that I'm using libcmaes in my project. Maybe we can close the issue..?

**Comment by beniz** [comment]
OK, please reopen when needed.
