### ISSUE TITLE
gcc compile issue

### ISSUE THREAD

**Issue by zheshen** [beniz/libcmaes#176]
Recently I’m trying to use the VD-CMA method to our C code. However, I’ve encounter some problems when installing the libcmaes when following the tutorial guidance. The compiling does not go through successfully and the output is a lot from which I’m not really sure what the problem is. Here’s the last three lines:
make[2]: *** [cmastrategy.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I also attached my Makefile if you can find some issues in it.
[Makefile.zip](https://github.com/beniz/libcmaes/files/1678021/Makefile.zip)

Here’s some background:
We run all jobs on the university HPC, and the default gcc on our cluster is an older version, therefore I installed gcc7.3 on my account. Also I want to install the libcmaes on my local folder. So maybe there are some libraries that are not in the default path

Do you have some advice on installing the library, something particular to pay attention to when not installing in the default way?

**Comment by beniz** [comment]
Hi, please provide the full compilation log.

**Comment by zheshen** [comment]
OK, please see the attachment.
[complication.log](https://github.com/beniz/libcmaes/files/1678744/complication.log)

**Comment by beniz** [comment]
The first error says
```
../cmaes_export.h:1:1: error: 'define' does not name a type; did you mean 'rewind'?
 define CMAES_EXPORT
 ^~~~~~
```
My guess is that you misstyped one of the setup step, as the `cmaes_export.h` file should contain `#define CMAES_EXPORT` and you appear to be missing the `#`.

**Comment by zheshen** [comment]
Thanks for pointing out the silly mistake. I think the installation works well and next I will figure out how to use it in my C code.
