### ISSUE TITLE
Compiling with C

### ISSUE THREAD

**Issue by zheshen** [beniz/libcmaes#177]
Hi.
What is the most straightforward way to use VD-CMA as a black box to optimize parameters in C code? It will be great if there are some similar examples or tutorials?

**Comment by beniz** [comment]
libcmaes is C++, for a pure C version, see https://github.com/CMA-ES/c-cmaes

**Comment by nikohansen** [comment]
@zheshen , I am not aware of a pure C implementation of VD-CMA, sorry.

**Comment by loshchil** [comment]
@zheshen @nikohansen There is a pure C implementation in 
void VDCMA of lmcma.cpp available at https://sites.google.com/site/ecjlmcma/
