### ISSUE TITLE
Maximizing a function

### ISSUE THREAD

**Issue by jrieffel** [beniz/libcmaes#186]
For optimization tasks like evolutionary robotics, where fitness is measured as distance traveled (something to me maximized), what is the most appropriate way to implement this in CMA-ES?  I cannot find a parameter setting.

**Comment by beniz** [comment]
Minimize -1*distance maybe ?

**Comment by jrieffel** [comment]
If I'm not mistaken it always minimizes toward 0. But maybe I'm mistaken?

**Comment by beniz** [comment]
There should be no bound to the min.

**Comment by nikohansen** [comment]
> If I'm not mistaken it always minimizes toward 0. But maybe I'm mistaken?

If "it" refers to CMA-ES or any numerical minimizer, the answer is yes, you are mistaken.  CMA-ES in particular minimizes any function x -> f(x) exactly the same (up to numerical errors) as x -> a f(x) + b for any real number a > 0 and any real number b.

**Comment by jrieffel** [comment]
Brilliant, thanks!
