### ISSUE TITLE
Bounding the parameters x

### ISSUE THREAD

**Issue by lihanwei** [beniz/libcmaes#187]
Setting up the example code of bounding the search area of parameter x, but it seems to not work right. When I do optimization using aCMAES, the result x is out of the set up.  Anyone gets same trouble like me?
Here is the code I used:

GenoPheno<pwqBoundStrategy> gp(lbounds, ubounds, dim);
CMAParameters<GenoPheno<pwqBoundStrategy>> cmaparams(InitPara, Config->Sigma[Level][6*step + 3], Config->Lamda[Level], 0, gp);
cmaparams._algo = aCMAES;
if (RigidDofDescriptor == T)
{
      cmaparams.set_fixed_p(0, 0.0f);
      cmaparams.set_fixed_p(1, 0.0f);
      cmaparams.set_fixed_p(2, 0.0f);
}
cmaparams.set_max_iter(Config->MaxIter[Level]);
CMASolutions cmasols = cmaes<GenoPheno<pwqBoundStrategy>>(ObjectiveFunction, cmaparams);
std::cout << "best solution: " << cmasols << std::endl;
std::cout << "optimization took " << cmasols.elapsed_time() / 1000.0 << " seconds\n";
Candidate bcand = cmasols.best_candidate();
double fmin = bcand.get_fvalue(); // min objective function value the optimizer converged to
Para.push_back(bcand.get_x()); // vector of objective function parameters at minimum.
double edm = cmasols.edm(); // expected distance to the minimum.

Result:
I set up each bounding area is [-30,30], but the optimization result get out of it. Sometimes get 50 or beyond. And the final function value is not equal to the optimize funciton value. I wonder why?

**Comment by beniz** [comment]
Hi, see https://github.com/beniz/libcmaes/issues/135#issuecomment-207941751 as you need to retrieve solution values rescaled for the initial state-space. This is because when using bounds, the internal state-space is automatically scaled.

**Comment by lihanwei** [comment]
Thank you very much! @beniz 
It works fine now.
