### ISSUE TITLE
Outdated README.md?

### ISSUE THREAD

**Issue by pi-q** [beniz/libcmaes#201]
When attempting to compile the library, we had two minor difficulties, that we could manually fix.

1. Prefix option 
`./configure --enable-python --with-prefix=/home/yourusername`
as described in README.md, produces the following warning:
`configure: WARNING: unrecognized options: --with-prefix` 
This was easily fixed with
`./configure --enable-python --prefix=/home/yourusername`

2. lgtest dependency
when running
`make`
it failed with
`/usr/bin/ld: cannot find -lgtest`
`/usr/bin/ld: cannot find -lgtest_main`
`collect2: error: ld returned 1 exit status`
`Makefile:812: recipe for target 'simple_test' failed`
Installing [googletest](https://github.com/google/googletest) has solved the issue.

Maybe this could easily be fixed by updating README.md and the list of dependencies?

**Comment by beniz** [comment]
Hi, thanks for your feedback. See https://github.com/beniz/libcmaes/commit/1d3b64a4e220393dfc64b3fe1652c0f323042043 for a fix of the `--prefix` documentation.

`gtest` is already listed in the dependencies, as optional.

Feel free to suggest any remaining changes directly as a pull request to the project!
