### ISSUE TITLE
Capture mistake of initializing diagonal cov matrix while using a full matrix algorithm (new title)

### ISSUE THREAD

**Issue by agrayver** [beniz/libcmaes#98]
By taking sample-code.cc and adding cmaparams.set_vd(); line after cmaparams.set_algo(aCMAES), it crashes with the following error:

main: /usr/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:301: Eigen::SelfAdjointEigenSolver<_MatrixType>::MatrixType Eigen::SelfAdjointEigenSolver<_MatrixType>::operatorInverseSqrt() const [with _MatrixType = Eigen::Matrix<double, -1, -1>; Eigen::SelfAdjointEigenSolver<_MatrixType>::MatrixType = Eigen::Matrix<double, -1, -1>]: Assertion `m_isInitialized && "SelfAdjointEigenSolver is not initialized."' failed.

**Comment by beniz** [comment]
Ha, it seems my last email came too late :)

Here, you're wrongly calling for aCMAES instead of VD-CMA. Do:
```
cmaparams.set_str_algo("vdcma");
```
which is equivalent to
```
cmaparams.set_algo(VD_CMAES);
cmaparams.set_vd();
```

I am leaving this ticket open to use it to capture the mistake and return a better error message.
